#!/usr/bin/env php

<?php 

require_once __DIR__ . '/vendor/autoload.php'; 

use Symfony\Component\Console\Application; 
use Webleit\DeleteSlackFiles\Command\DeleteFilesCommand;

$app = new Application();

$app->add(new DeleteFilesCommand());

$app->run();